version: "3"
services:
  app:
    container_name: layendan-web
    working_dir: /app
    build:
      context: ./app

  nginx:
    container_name: layendan-web-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - 80:80
      - 443:443