version: "3"
services:
  app:
    container_name: layendan-web
    working_dir: /app
    build:
      context: ./app
      target: dev
    volumes:
      - ./app/src:/app/src
      - ./app/.svelte-kit/:/app/.svelte-kit
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
